server:
  port: 8761

eureka:
  instance:
    # В Docker нельзя рекламировать себя как localhost,
    # иначе клиенты будут пытаться подключаться к себе, а не к контейнеру discovery-server.
    hostname: discovery-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

spring:
  application:
    name: discovery-server

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF